name: llm_hf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2.0
  - ipywidgets
  - jupyterlab
  - pip:
      - torch==2.2.2
      - transformers==4.38.2
      - sentencepiece==0.2.0
      - pillow==11.2.1
